### ISSUE TITLE
about build step

### ISSUE THREAD

**Issue by KenChen-Xeniro** [ilaychen/ECDSA-OpenCL#1]
hi,ilaychen,
it looks  interesting, 
when i am trying to build a demo about ecdsa signature or verify  for gpu ,which folder should i build  ?

**Comment by ilaychen** [comment]
Hey, you should take a look at secp256k1-opencl dir, but only in a few weeks, cause we're still working on it at the moment

**Comment by KenChen-Xeniro** [comment]
Thanks,
looking forward to your new progress
